DevEnum attributes can now be directly assigned labels
tango-controls/pytango pull request #221
Opened 2018-10-01 14:17 UTC by jairomoldes

Following #194 I think that it would be nice to allow directly assigning labels to DevEnum attributes. For example if you have a "Planet" DevEnum attribute with labels ('Mercury', 'Saturn', 'Mars') it would be nice to allow writing:
```
dev.Planet = 'Mercury'
```
I you agree please wait to merge: I will update documentation and create a new test.

2018-10-01 21:13 UTC, ajoubertza requested changes
Thanks @jairomoldes.  I like the idea.  It will make for simpler client code.   A little shorter than
`dev.Planet = dev.Planet.Mercury`.

2018-10-01 21:13 UTC, ajoubertza commented on tango/device_proxy.py
> +                if enum_class and type(value)==str:
Suggest using the utility function `is_pure_str`, rather than this direct type check.  See:
https://github.com/tango-controls/pytango/blob/f600539/tango/utils.py#L468

2018-10-01 21:13 UTC, ajoubertza commented on tango/device_proxy.py
> +                    except:
As a general note, bare `except:` statements should be avoided.  If we don't know what type of exceptions to expect, then at least use `except Exception:`.  See the [PEP-008 guide](https://www.python.org/dev/peps/pep-0008/#programming-recommendations) for notes (search for "bare").

In this particular case, it looks like catching `KeyError` here would be sufficient.

2018-10-01 21:13 UTC, ajoubertza commented on tango/device_proxy.py
> +            pass
I'm not sure why we need two levels of `try..except` statements here?  The call to `self.__get_attr_cache().get(name_l)` is pretty safe.  It will return `None` if the attribute is not cached.

Wouldn't something like this work:
```
    attr_info = self.__get_attr_cache().get(name_l)
    if attr_info:
        _, enum_class = attr_info
        if enum_class and is_pure_str(value):
            try:
                # allow writing DevEnum attributes using label name
                value = enum_class[value]
            except KeyError:
                raise AttributeError('Invalid Enum value %s for %s' % (value, name))
        return self.write_attribute(name, value)
```

2018-10-01 21:13 UTC, ajoubertza commented on tango/device_proxy.py
> +                        raise AttributeError('Invalid Enum value %s' % value)
It would be useful to report some information about the attribute that caused the problem.  At least include the attribute name in the error message.  The valid labels could also be extracted with something like
`[m for m in enum_class.__members__]`

2018-10-01 21:13 UTC, ajoubertza commented on tango/device_proxy.py
>      if name_l in self.__get_pipe_cache():
Also note on line 342 there is another attempt to write to the attribute.  This will happen if the attribute wasn't already in the cache, but did become available after refreshing the cache on line 337.

Suggest moving the bulk of the new changes into a utility method that can be called from both places.  Similar to how the getattr method uses `__get_attribute_value` .

2018-10-26 11:40 UTC, vxgmichel commented
Hi all, I just fixed the CI.

2018-11-05 15:37 UTC, jairomoldes commented
Implemented the suggestions by @ajoubertza, updated documention and tests.

Please note that I used --force in order to keep a cleaner git history.

2018-11-08 07:19 UTC, ajoubertza approved these changes
This looks great, @jairomoldes!  I like the improvements to the example, and thanks for updating the docs.

Minor side note:  using `--force` to rewrite the history may look cleaner, but it makes reviewing harder since the changes since the previous review are lost.

2018-11-09 08:36 UTC, ajoubertza commented
@jairomoldes You can merge this.

2018-11-09 13:31 UTC, merged