test context support for memorized attributes
tango-controls/pytango pull request #384
Opened 2020-09-24 03:02 UTC by DrewDevereux

This pull request provides `DeviceTestContext` and `MultiDeviceTestContext` support for memorized attributes.
This has value because allows lightweight testing of device initialisation where device attributes are memorized.

The implementation provides a "memorized" argument this is handled just like the "properties" argument:
* For `DeviceTestContext`, a new constructor argument is added:
  ```
  with DeviceTestContext(TestDevice, memorized={"attr": "1"}) as proxy:
     asserty proxy.attr == 1
  ```
* For `MultiDeviceTestContext`, the device_info structure has a new `memorized` key:
  ```
  devices_info = (
      {
          "class": TestDevice,
          "devices": [
              {
                  "name": "test/device1/1",
                  "memorized": {"attr": "1"}
              },
          ]
      }
  )
  with MultiDeviceTestContext(devices_info) as context:
      proxy = context.get_device("test/device1/1")
      assert proxy.attr == 1
```

2020-10-10 12:05 UTC, ajoubertza requested changes
Great addition - thanks!  Minor changes requested.

The Codacy CI warning can be ignored.

2020-10-10 12:05 UTC, ajoubertza commented on tango/test_context.py
> +                    "__value": memorized_value
Well done figuring how to get this into the file database!  I had no idea.

2020-10-10 12:05 UTC, ajoubertza commented on tango/test_context.py
> +                 memorized=None, db=None, host=None, port=0, debug=3,
How about putting this new item as the last kwarg, to avoid a breaking API change?

2020-10-10 12:05 UTC, ajoubertza commented on tests/test_test_context.py
> +    attribite that is memorized or not, according to its boolean
Typo:
```suggestion
    attribute that is memorized or not, according to its boolean
```

2020-10-12 01:16 UTC, DrewDevereux commented on tango/test_context.py
> +                 memorized=None, db=None, host=None, port=0, debug=3,
Great idea! Done.

2020-10-12 01:16 UTC, DrewDevereux commented on tests/test_test_context.py
> +    attribite that is memorized or not, according to its boolean
Thanks, fixed. I squashed my commits too.

2020-10-12 01:18 UTC, DrewDevereux commented on tango/test_context.py
> +                    "__value": memorized_value
Actually I got it from https://www.tango-controls.org/developers/howto/how-pytango/ so credit to @tiagocoutinho I guess. :-)

2020-10-16 19:15 UTC, ajoubertza approved these changes
Looks good, thanks.

2020-10-16 19:15 UTC, merged