Windows 9.3.2
tango-controls/pytango pull request #395
Opened 2020-12-03 19:36 UTC by spirit1317

Fixes #369 Fixes #355

2020-12-04 06:45 UTC, ajoubertza commented
@spirit1317 Thanks for the PR.  It looks like this is based on the v9.3.2 tag, rather than the head of the develop branch.  Can you please merge the latest develop branch in to this one?  Or better yet, rebase this branch on the head of develop.  I think that will fix the CI problems on Travis related to pytest.

2020-12-04 08:23 UTC, ajoubertza requested changes
Nice work.  Most import change required is to make the AppVeyor build correctly report failure if any tests fail.

2020-12-04 08:23 UTC, ajoubertza commented on tests/conftest.py
> +    """ collets all tests to be run and outputs to bat script """
Typo: collets -> Collects

2020-12-04 08:23 UTC, ajoubertza commented on tests/conftest.py
> +        script_path = os.path.join(os.path.dirname(__file__),'run_tests_win.bat')
There are many PEP8 violations in this file.  Please run something like `black tests/conftest.py` to fix it.  Or `flake8` to point them out, and fix manually.  In this line, missing a space after the comma. 

It looks like the automatic Codacy quality check is no longer working for PRs.  It has been "missing" for the last few PRs.

2020-12-04 08:23 UTC, ajoubertza commented on appveyor.yml
> +  - cmd: if %PYTHON_VER%==27 "%PYTHON_ROOT%/Scripts/pip.exe" install enum34 futures trollius zipp
We shouldn't need to install all these packages manually, since they are in `setup.py` as test requirements. 

It should work if we use:
```
python setup.py test '-c pytest_empty_config.txt --collect-only -q -q tests'
```
instead of
```
pytest.exe -c pytest_empty_config.txt --collect-only -q -q tests
```

The benefit of using `python setup.py test` is that it reduces maintenance.   If we change requirements in  `setup.py` in future, we don't have to change `appveyor.yml` as well. 

The downside of using `python setup.py test`, is that it will install all those packages for every single test.  That will probably increase the time to run the tests unnecessarily.

Also note that there are some specific version limits in [`setup.py`](https://github.com/tango-controls/pytango/blob/cb9b202e6451b744e2a1847c1ae49b213e521fc1/setup.py#L488-L498) - we must match that in the AppVeyor config.  For both Python 2 and Python 3.

Conclusion:  install the test requirements manually.  However, make a change to use the correct package versions.

2020-12-04 08:23 UTC, ajoubertza commented on tests/conftest.py
> +                f.truncate()
Missing newline at the end of the file.  Please add one.

2020-12-04 08:23 UTC, ajoubertza commented on appveyor.yml
> +  - cmd: powershell -command "$body = Get-Content summary.json -Raw; Invoke-Webrequest $env:API_URL -Method 'POST' -UseBasicParsing -ContentType 'application/json; charset=utf-8' -Body $body"
This is nice! 

I see on AppVeyor that 75 to 77 of the tests have failed, yet the build is still green.   Two questions:
- Can we make the overall build fail (red), if any tests fail?
- What is causing those test failures?

2020-12-04 08:23 UTC, ajoubertza commented on appveyor.yml
> +  - appveyor DownloadFile https://github.com/spirit1317/tango-test-exe/raw/main/TangoTest.exe
Not ideal, but we can use this until there is a better solution.

In the readme on that repo, could you add the exact commands you used to build the executable, please?

2020-12-10 18:04 UTC, spirit1317 commented
Hello, I changed the code according to your comments:

- codacy improoved
- merged windows_9.3.2 with develop
- added pip packages versions to appveyor.yml
- all tests are passing on Windows, but I had to remove `process=True` from `with DeviceTestContext(process=True)`. Also only one DeviceTestContest can be used per test as you know, so I had to rewrite some tests in test_server.py, but the coverage is the same (please take a look).
- if (in future) some test fail, the appveyor buld will not pass green
- added readme.md to TangoTest.exe repo, but I didn't build TangoTest it myself
- all tests are passing also on Linux on travis, however I had problems with get_attribute_config() on my computer

2020-12-11 06:56 UTC, andygotz commented
Impressive - well done! I look forward to a new package in pip to try out. How much work is that?

2020-12-11 20:49 UTC, ajoubertza requested changes

2020-12-11 20:49 UTC, ajoubertza commented on tests/test_server.py
> +def test_device_property(typed_values, server_green_mode):
These new versions of the property tests don't quite cover the same functionality as before.  I also prefer the old names for the tests.  Here's an update that uses your ideas, but keeps the test functionality and names the same.

```python
def test_device_property_no_default(typed_values, server_green_mode):
    dtype, values, expected = typed_values
    patched_dtype = dtype if dtype != (bool,) else (int,)
    value = values[1]

    class TestDevice(Device):
        green_mode = server_green_mode

        prop_without_db_value = device_property(dtype=dtype)
        prop_with_db_value = device_property(dtype=dtype)

        @command(dtype_out=bool)
        def is_prop_without_db_value_set_to_none(self):
            return self.prop_without_db_value is None

        @command(dtype_out=patched_dtype)
        def get_prop_with_db_value(self):
            return self.prop_with_db_value

    with DeviceTestContext(TestDevice,
                           properties={'prop_with_db_value': value}) as proxy:
        assert proxy.is_prop_without_db_value_set_to_none()
        assert_close(proxy.get_prop_with_db_value(), expected(value))


def test_device_property_with_default_value(typed_values, server_green_mode):
    dtype, values, expected = typed_values
    patched_dtype = dtype if dtype != (bool,) else (int,)

    default = values[0]
    value = values[1]

    class TestDevice(Device):
        green_mode = server_green_mode

        prop_without_db_value = device_property(
            dtype=dtype, default_value=default
        )
        prop_with_db_value = device_property(
            dtype=dtype, default_value=default
        )

        @command(dtype_out=patched_dtype)
        def get_prop_without_db_value(self):
            return self.prop_without_db_value

        @command(dtype_out=patched_dtype)
        def get_prop_with_db_value(self):
            return self.prop_with_db_value

    with DeviceTestContext(TestDevice,
                           properties={'prop_with_db_value': value}) as proxy:
        assert_close(proxy.get_prop_without_db_value(), expected(default))
        assert_close(proxy.get_prop_with_db_value(), expected(value))
```

2020-12-11 20:49 UTC, ajoubertza commented on tests/test_server.py
> -
This test case was important.  It checks that mandatory properties that have values specified in the database, work correctly.

Here's is a version that tests both cases:
- works if a value is specified in the database
- raises an error if not specified in the database

We now have to split it into two different tests.

```python
def test_mandatory_device_property_with_db_value_succeeds(
        typed_values, server_green_mode):
    dtype, values, expected = typed_values
    patched_dtype = dtype if dtype != (bool,) else (int,)
    default, value = values[:2]

    class TestDevice(Device):
        green_mode = server_green_mode

        prop = device_property(dtype=dtype, mandatory=True)

        @command(dtype_out=patched_dtype)
        def get_prop(self):
            return self.prop

    with DeviceTestContext(TestDevice,
                           properties={'prop': value}) as proxy:
        assert_close(proxy.get_prop(), expected(value))


def test_mandatory_device_property_without_db_value_fails(
        typed_values, server_green_mode):
    dtype, _, _ = typed_values

    class TestDevice(Device):
        green_mode = server_green_mode
        prop = device_property(dtype=dtype, mandatory=True)

    with pytest.raises(DevFailed) as context:
        with DeviceTestContext(TestDevice):
            pass
    assert 'Device property prop is mandatory' in str(context.value)

```

2020-12-13 19:19 UTC, ajoubertza commented on appveyor.yml
> +  - "%PYTHON_ROOT%/Scripts/pip.exe install \"gevent!=1.5a1\" pytest psutil \"six>=1.10\" \"numpy>=1.1\" enum34"
Thanks for the fixes to the versions.

Note that `enum34` is only for Python 2.  It is a back-port of the enum code from Python 3.4, so needed on versions of Python < 3.4.

2020-12-13 19:19 UTC, ajoubertza commented on setup.py
> +class CheckTestsErrors(Command):
Nice idea to do this check via Python code.  A lot easier than from the Windows command line!

2020-12-13 19:19 UTC, ajoubertza commented on setup.py
> +        ("ignore-gevent-errors",None,"Failed tests using GreenMode.Gevent will not raise error."),
Please run a linter over you new changes - should be spaces after commas in the tuples, for PEP8.  Also in the lists and function argument lists below.

2020-12-13 19:19 UTC, ajoubertza commented on setup.py
> +            summary = json.loads(summary)
This is fine, but note that `json.load` will read and load from the file in one step (instead of a `read` and `loads`).

2020-12-13 19:19 UTC, ajoubertza commented on setup.py
> +        'check_tests_errors': CheckTestsErrors}
I see all the other command classes are using lower case.  How about we keep this one lower case as well, to match that convention?  `check_tests_errors`.

2020-12-14 11:09 UTC, spirit1317 commented
Hi,

I compled with your latest remarks. Additionally:

- On some environments few Gevent tests were failing. You asked to drop for now Gevent support for those enviroments and let the build pass with those errors. I use setup.py command `check_tests_errors` with flag `--ignore-gevent-errors` in combination with [GEVENT_NOT_SUPPORTED](https://github.com/spirit1317/pytango/blob/3502427ef34445cc0d5c9dbc5ef53dc62590a61e/appveyor.yml#L51) `appveyor.yml` environment variable. This variable can be deleted when we find the cause of those errors.

- I tried to debug the issue with failing `test_identity_command` with Gevent. Sometimes one of the `bytes_devstring` from test_utils.TYPED_VALUES in the list of 10 same elements gets truncated and end letters are changed. What I found is the command arguments are not passed to device command correctly. It happens after "allways_executed_hook" is called, but this function does nothing so, its not causing the problem. Following the call stack:
[connection.py:137](https://github.com/spirit1317/pytango/blob/3502427ef34445cc0d5c9dbc5ef53dc62590a61e/tango/connection.py#L137) is ok
[server.py:1142](https://github.com/spirit1317/pytango/blob/3502427ef34445cc0d5c9dbc5ef53dc62590a61e/tango/server.py#L1142) the args strings are truncated
Please see next comment.

2020-12-14 11:20 UTC, spirit1317 commented
Heres the simple code, that can replicate the issue from previous comment without using pytest:
```python
import sys
import six

from tango import GreenMode
from tango.server import Device
from tango.server import command
from tango.test_utils import DeviceTestContext, TYPED_VALUES

values = TYPED_VALUES[(str,)]

class TestDevice(Device):
    green_mode = GreenMode.Gevent

    @command(dtype_in=(str,), dtype_out=(str,))
    def identity(self, arg):
        return arg

with DeviceTestContext(TestDevice, timeout=600) as proxy:
    for value in values:
        result = proxy.identity(value)
```

Heres a screen shot of full debug stack (list of strings shown in args is already truncated on this line):
![call_stack](https://user-images.githubusercontent.com/41666803/102074637-5a8ed200-3e05-11eb-99a5-fcb49e85f12b.png)

2020-12-14 19:55 UTC, ajoubertza commented
Thanks for the details on the gevent issue.  We can fix it one day, if someone really needs the support.

2020-12-14 19:57 UTC, ajoubertza approved these changes
Looks good - nice work, @spirit1317!

I changed the target of the PR merge to the `develop` branch, instead of `stable`.  The diff looks much better now.  We only update `stable` when making a release.

2020-12-14 19:58 UTC, merged